title       = 'likeliHUD'
project     = 'likeliHUD'
description = 'A simple UI library for LOVE2D'
dir         = 'doc'
format      = 'markdown'
readme      = 'README.md'
file        = { 'likelihud/Block.lua',
                'likelihud/Layout.lua',
                'likelihud/Rectangle.lua',
                'likelihud/Image.lua',
                'likelihud/Stack.lua',
                'likelihud/Label.lua' }
examples    = {'examples'}
