-- Automatically generated by an Aseprite script
return
{
	["zoom"] = 1,
	["two"] = {
		["y"] = 56,
		["height"] = 36,
		["width"] = 36,
		["x"] = 20,
	}
,
	["four"] = {
		["y"] = 150,
		["height"] = 40,
		["width"] = 102,
		["x"] = 40,
	}
,
	["one"] = {
		["y"] = 10,
		["height"] = 24,
		["width"] = 160,
		["x"] = 20,
	}
,
	["three"] = {
		["y"] = 94,
		["height"] = 26,
		["width"] = 84,
		["x"] = 94,
	}
,
}
